# Base configs
# baseurl: "https://photography.rampatra.com"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
# google_analytics: "UA-46465113-2"

# UI configs
title: "Portfolio by Giulia Ferrari"
subtitle: "See the world through my maps!"
author: "Giulia Ferrari"
header:
  title: "Maps"
  subtitle: "by Giulia Ferrari"
footer:
  name: "Hey there, my name is Giulia"
  bio: "I am a GIS technician passionate about spacial analysis, visual representations and all forms of creative arts."
#  github: "Want a website like this for yourself for free? Just <a href=\"https://github.com/ramswaroop/photography\">fork me on github</a> ;)"
web_design: "AJ"
social_urls:
  # facebook: "https://www.facebook.com/ramswaroop"
  # twitter: "https://www.twitter.com/ram__patra"
  instagram: "https://www.instagram.com/giulia.ferrari0917"
  # dribbble: "https://dribbble.com/rampatra"
  linkedin: "https://www.linkedin.com/in/giuliaferrarigis/"
  github: "https://www.github.com/gfgis"
